import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { httpBatchLink } from "@trpc/client";
import { trpc } from "@/lib/trpc";
import App from "./App";
import "./styles.css";
const queryClient=new QueryClient({defaultOptions:{queries:{staleTime:30_000,retry:1}}});
const trpcClient=trpc.createClient({links:[httpBatchLink({url:"/api/trpc"})]});
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><trpc.Provider client={trpcClient} queryClient={queryClient}><QueryClientProvider client={queryClient}><App/></QueryClientProvider></trpc.Provider></React.StrictMode>);
