-- Base de conhecimento importada do EJC (Zai GLM): balde genérico para os
-- tipos de documento sem tabela própria no Atlas, mais uma biblioteca de
-- legislação citável independentemente e a suíte de QA do RAG.
CREATE TABLE IF NOT EXISTS knowledge_documents (id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(191) NOT NULL UNIQUE,title VARCHAR(500) NOT NULL,document_type ENUM('peca','contrato','checklist','fluxo','tabela_documentos','triagem','prazo','doutrina','regra_inteligencia','regras_contratuais') NOT NULL,area VARCHAR(64) NOT NULL,subarea VARCHAR(128) NULL,subject VARCHAR(255) NULL,subsubject VARCHAR(255) NULL,priority ENUM('P0','P1','P2','P3') NOT NULL DEFAULT 'P2',batch_id INT NULL,content LONGTEXT NOT NULL,metadata JSON NULL,tags JSON NULL,source_label VARCHAR(255) NULL,official_url VARCHAR(1024) NULL,consulted_at DATE NULL,source_status ENUM('official_confirmed','attachment_reviewed','editorial_review','secondary_pending','not_for_use') NOT NULL DEFAULT 'editorial_review',status ENUM('ativo','revisao_humana','desativado','demonstracao') NOT NULL DEFAULT 'revisao_humana',fictitious INT NOT NULL DEFAULT 0,active INT NOT NULL DEFAULT 1,version INT NOT NULL DEFAULT 1,verified_at DATE NULL,next_verification_recommended_at DATE NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_knowledge_documents_type(document_type),KEY idx_knowledge_documents_area(area,subarea),KEY idx_knowledge_documents_priority(priority),KEY idx_knowledge_documents_status(status),CONSTRAINT fk_knowledge_documents_batch FOREIGN KEY(batch_id) REFERENCES ingestion_batches(id) ON DELETE SET NULL ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knowledge_chunks (id INT AUTO_INCREMENT PRIMARY KEY,document_id INT NOT NULL,position INT NOT NULL,context VARCHAR(500) NULL,text LONGTEXT NOT NULL,word_count INT NOT NULL DEFAULT 0,embedding LONGTEXT NULL,KEY idx_knowledge_chunks_document(document_id),CONSTRAINT fk_knowledge_chunks_document FOREIGN KEY(document_id) REFERENCES knowledge_documents(id) ON DELETE CASCADE ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS knowledge_relationships (id INT AUTO_INCREMENT PRIMARY KEY,source_document_id INT NOT NULL,target_document_id INT NOT NULL,relation_type VARCHAR(64) NOT NULL,description TEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_knowledge_relationship(source_document_id,target_document_id,relation_type),KEY idx_knowledge_relationships_source(source_document_id),KEY idx_knowledge_relationships_target(target_document_id),KEY idx_knowledge_relationships_type(relation_type),CONSTRAINT fk_knowledge_relationships_source FOREIGN KEY(source_document_id) REFERENCES knowledge_documents(id) ON DELETE CASCADE ON UPDATE RESTRICT,CONSTRAINT fk_knowledge_relationships_target FOREIGN KEY(target_document_id) REFERENCES knowledge_documents(id) ON DELETE CASCADE ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS legislation_library (id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(191) NOT NULL UNIQUE,title VARCHAR(500) NOT NULL,norm VARCHAR(255) NOT NULL,provision VARCHAR(255) NULL,area VARCHAR(64) NOT NULL,subarea VARCHAR(128) NULL,content LONGTEXT NOT NULL,official_url VARCHAR(1024) NOT NULL,source_label VARCHAR(255) NULL,consulted_at DATE NOT NULL,source_status ENUM('official_confirmed','attachment_reviewed','editorial_review','secondary_pending','not_for_use') NOT NULL DEFAULT 'official_confirmed',verified_at DATE NULL,version INT NOT NULL DEFAULT 1,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_legislation_library_norm(norm),KEY idx_legislation_library_area(area,subarea)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rag_tests (id INT AUTO_INCREMENT PRIMARY KEY,question TEXT NOT NULL,answer LONGTEXT NULL,found_documents JSON NULL,score DECIMAL(5,2) NULL,status ENUM('pendente','sucesso','parcial','falha') NOT NULL DEFAULT 'pendente',observation TEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_rag_tests_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
