// EJC — Taxonomia jurídica padronizada (item 20 da missão)
// Regra: evitar múltiplas tags diferentes para o mesmo conceito.
// Formato de tag: <area>/<subarea>

export interface AreaTaxonomia {
  id: string;
  nome: string;
  subareas: { id: string; nome: string }[];
}

export const AREAS: AreaTaxonomia[] = [
  {
    id: 'ambiental',
    nome: 'Direito Ambiental',
    subareas: [
      { id: 'licenciamento', nome: 'Licenciamento Ambiental' },
      { id: 'auto-infracao', nome: 'Auto de Infração Ambiental' },
      { id: 'responsabilidade-civil', nome: 'Responsabilidade Civil Ambiental' },
      { id: 'responsabilidade-administrativa', nome: 'Responsabilidade Administrativa' },
      { id: 'responsabilidade-penal', nome: 'Responsabilidade Penal' },
      { id: 'vegetacao', nome: 'Vegetação — APP e Reserva Legal' },
      { id: 'recursos-hidricos', nome: 'Recursos Hídricos' },
      { id: 'residuos', nome: 'Resíduos Sólidos' },
      { id: 'fauna', nome: 'Fauna' },
      { id: 'tac', nome: 'TAC e Regularização' },
      { id: 'acao-civil-publica', nome: 'Ação Civil Pública Ambiental' },
      { id: 'codigo-ambiental-mg', nome: 'Código Ambiental — Minas Gerais' },
    ],
  },
  {
    id: 'tributario',
    nome: 'Direito Tributário',
    subareas: [
      { id: 'execucao-fiscal', nome: 'Execução Fiscal' },
      { id: 'decadencia-prescricao', nome: 'Decadência e Prescrição' },
      { id: 'simples-nacional', nome: 'Simples Nacional' },
      { id: 'icms', nome: 'ICMS' },
      { id: 'icms-mg', nome: 'ICMS — Minas Gerais' },
      { id: 'itcd', nome: 'ITCD' },
      { id: 'ipva', nome: 'IPVA' },
      { id: 'taxas-mg', nome: 'Taxas Estaduais — Minas Gerais' },
      { id: 'defesa-administrativa-mg', nome: 'Defesa Administrativa Fiscal — MG' },
      { id: 'pis-cofins', nome: 'PIS/COFINS' },
      { id: 'carf', nome: 'CARF e Defesa Administrativa' },
      { id: 'pgfn', nome: 'PGFN e Transação' },
      { id: 'obrigacao-tributaria', nome: 'Obrigação Tributária e Sujeição Passiva' },
      { id: 'mandado-de-seguranca', nome: 'Mandado de Segurança Tributário' },
      { id: 'competencia-imunidades', nome: 'Competência, Vedações e Imunidades' },
      { id: 'principios', nome: 'Princípios Tributários' },
      { id: 'legislacao-tributaria', nome: 'Legislação Tributária (CTN)' },
      { id: 'iss', nome: 'ISS — Imposto sobre Serviços' },
      { id: 'compensacao', nome: 'Compensação e Restituição' },
      { id: 'transacao-tributaria', nome: 'Transação Tributária' },
      { id: 'contribuicoes-sociais', nome: 'Contribuições Sociais (Seguridade)' },
      { id: 'geral', nome: 'Tributário — Geral' },
    ],
  },
  {
    id: 'administrativo',
    nome: 'Direito Administrativo e Licitações',
    subareas: [
      { id: 'licitacao-14133', nome: 'Licitações — Lei 14.133/2021' },
      { id: 'contratos-administrativos', nome: 'Contratos Administrativos' },
      { id: 'sancoes', nome: 'Sanções Administrativas' },
      { id: 'improbidade', nome: 'Improbidade Administrativa' },
      { id: 'mandado-seguranca', nome: 'Mandado de Segurança' },
    ],
  },
  {
    id: 'trabalhista',
    nome: 'Direito do Trabalho',
    subareas: [
      { id: 'vinculo', nome: 'Vínculo Empregatício' },
      { id: 'rescisao', nome: 'Verbas Rescisórias' },
      { id: 'jornada', nome: 'Jornada e Horas Extras' },
      { id: 'terceirizacao', nome: 'Terceirização' },
      { id: 'fiscalizacao', nome: 'Fiscalização Trabalhista' },
      { id: 'processo-trabalho', nome: 'Reclamatória Trabalhista e Recursos' },
      { id: 'gratuidade-custas', nome: 'Gratuidade, Custas e Honorários' },
    ],
  },
  {
    id: 'civil',
    nome: 'Direito Civil',
    subareas: [
      { id: 'responsabilidade-civil', nome: 'Responsabilidade Civil' },
      { id: 'contratos', nome: 'Contratos e Obrigações' },
      { id: 'cobranca', nome: 'Cobrança e Inadimplemento' },
      { id: 'propriedade', nome: 'Propriedade e Posse' },
      { id: 'doacao', nome: 'Doação' },
      { id: 'decadencia-prescricao', nome: 'Decadência e Prescrição Civil' },
      { id: 'familia', nome: 'Família e Sucessões' },
    ],
  },
  {
    id: 'processual-civil',
    nome: 'Processo Civil',
    subareas: [
      { id: 'tutela-urgencia', nome: 'Tutela de Urgência' },
      { id: 'contestacao', nome: 'Contestação e Defesa' },
      { id: 'recursos', nome: 'Recursos' },
      { id: 'execucao', nome: 'Cumprimento de Sentença e Execução' },
      { id: 'intervencao-terceiros', nome: 'Intervenção de Terceiros' },
      { id: 'prazos', nome: 'Prazos Processuais' },
      { id: 'juizados-especiais', nome: 'Juizados Especiais (JEC/JECrim/JEF/JF)' },
      { id: 'cejusc', nome: 'CEJUSC e Conciliação' },
      { id: 'propriedade', nome: 'Ações Reais e Propriedade' },
      { id: 'mandado-de-seguranca', nome: 'Mandado de Segurança Cível' },
      { id: 'possessorias', nome: 'Ações Possessórias' },
      { id: 'citacoes-editais', nome: 'Citações e Editais' },
      { id: 'registral', nome: 'Via Registral e Extrajudicial' },
    ],
  },
  {
    id: 'consumidor',
    nome: 'Direito do Consumidor',
    subareas: [
      { id: 'fato-produto-servico', nome: 'Fato do Produto e Serviço' },
      { id: 'vicios', nome: 'Vícios do Produto e Serviço' },
      { id: 'negativacao', nome: 'Negativação e Cadastro' },
      { id: 'cobranca', nome: 'Cobrança de Dívidas' },
      { id: 'servicos-digitais', nome: 'Serviços Digitais e Marketplaces' },
      { id: 'fazenda-publica', nome: 'Consumidor x Fazenda Pública' },
      { id: 'fato-do-produto', nome: 'Fato do Produto (Capítulos Temáticos)' },
      { id: 'recall', nome: 'Recall e Anúncios' },
      { id: 'credito-e-financiamento', nome: 'Crédito e Financiamento' },
      { id: 'clausulas-abusivas', nome: 'Cláusulas Abusivas' },
      { id: 'cobranca-e-indebito', nome: 'Cobrança e Indébito' },
      { id: 'publicidade-oferta', nome: 'Publicidade e Oferta' },
      { id: 'contratos-consumidor', nome: 'Contratos de Consumo' },
      { id: 'defesa-em-juizo', nome: 'Defesa do Consumidor em Juízo' },
      { id: 'atendimento-sac', nome: 'SAC e Atendimento Eletrônico' },
      { id: 'atendimento-extrajudicial-mg', nome: 'Atendimento Extrajudicial — MG' },
      { id: 'geral', nome: 'Consumidor — Geral' },
    ],
  },
  {
    id: 'bancario',
    nome: 'Direito Bancário',
    subareas: [
      { id: 'alienacao-fiduciaria', nome: 'Alienação Fiduciária e Busca e Apreensão' },
      { id: 'juros-tarifas', nome: 'Juros e Tarifas' },
      { id: 'revisao-contratual', nome: 'Revisão Contratual' },
      { id: 'fraude', nome: 'Fraude e Responsabilidade Bancária' },
      { id: 'contratos-bancarios', nome: 'Contratos Bancários e Cláusulas' },
    ],
  },
  {
    id: 'empresarial',
    nome: 'Direito Empresarial',
    subareas: [
      { id: 'contratos-empresariais', nome: 'Contratos Empresariais' },
      { id: 'sociedades', nome: 'Sociedades e Sócios' },
      { id: 'recuperacao-judicial', nome: 'Recuperação Judicial e Falência' },
      { id: 'compliance', nome: 'Compliance e Due Diligence' },
    ],
  },
  {
    id: 'penal',
    nome: 'Direito Penal e Processo Penal',
    subareas: [
      { id: 'crimes-ambientais', nome: 'Crimes Ambientais' },
      { id: 'honra', nome: 'Crimes contra a Honra' },
      { id: 'crimes-patrimoniais', nome: 'Crimes Patrimoniais' },
      { id: 'provas', nome: 'Provas e Cautelares' },
      { id: 'prescricao-penal', nome: 'Prescrição Penal' },
      { id: 'jecrim-menor-ofensividade', nome: 'JECrim — Menor Potencial Ofensivo' },
      { id: 'teoria-do-crime', nome: 'Teoria do Crime' },
      { id: 'aplicacao-lei-penal', nome: 'Aplicação da Lei Penal' },
      { id: 'prisoes-cautelares', nome: 'Prisões e Medidas Cautelares' },
      { id: 'garantias', nome: 'Garantias Constitucionais Penais' },
      { id: 'geral', nome: 'Penal — Geral' },
    ],
  },
  {
    id: 'digital',
    nome: 'LGPD e Direito Digital',
    subareas: [
      { id: 'bases-legais', nome: 'Bases Legais e Tratamento de Dados' },
      { id: 'incidentes', nome: 'Incidentes e Vazamentos' },
      { id: 'anpd', nome: 'ANPD e Regulação' },
      { id: 'dados-sensiveis', nome: 'Dados Pessoais Sensíveis' },
      { id: 'criancas-adolescentes', nome: 'Crianças e Adolescentes' },
      { id: 'transferencia-internacional', nome: 'Transferência Internacional de Dados' },
      { id: 'ia', nome: 'Inteligência Artificial' },
    ],
  },
  {
    id: 'geral',
    nome: 'Transversal / Geral',
    subareas: [
      { id: 'prazos', nome: 'Prazos Gerais' },
      { id: 'metodologia', nome: 'Metodologia EJC' },
      { id: 'triagem', nome: 'Triagem Geral' },
    ],
  },
];

export function areaNome(id: string): string {
  return AREAS.find((a) => a.id === id)?.nome ?? id;
}

export function subareaNome(area: string, subarea: string): string {
  const a = AREAS.find((x) => x.id === area);
  return a?.subareas.find((s) => s.id === subarea)?.nome ?? subarea;
}

// Tags canônicas do lote P0 (evita sinonímia — item 20)
export const TAGS_CANONICAS_P0 = [
  'ambiental/auto-infracao',
  'ambiental/licenciamento',
  'ambiental/responsabilidade-civil',
  'ambiental/responsabilidade-administrativa',
  'ambiental/responsabilidade-penal',
  'ambiental/vegetacao',
  'ambiental/acao-civil-publica',
  'ambiental/residuos',
  'processual-civil/tutela-urgencia',
  'processual-civil/prazos',
  'processual-civil/contestacao',
  'processual-civil/juizados-especiais',
  'processual-civil/intervencao-terceiros',
  'processual-civil/possessorias',
  'processual-civil/citacoes-editais',
  'processual-civil/registral',
  'civil/decadencia-prescricao',
  'civil/doacao',
  'civil/usucapiao',
  'tributario/decadencia-prescricao',
  'tributario/execucao-fiscal',
  'tributario/icms-mg',
  'tributario/itcd',
  'tributario/ipva',
  'tributario/taxas-mg',
  'tributario/defesa-administrativa-mg',
  'ambiental/codigo-ambiental-mg',
  'processual-civil/cejusc',
  'processual-civil/propriedade',
  'processual-civil/mandado-de-seguranca',
  'tributario/obrigacao-tributaria',
  'tributario/mandado-de-seguranca',
  'consumidor/fato-do-produto',
  'consumidor/recall',
  'consumidor/credito-e-financiamento',
  'consumidor/clausulas-abusivas',
  'consumidor/cobranca-e-indebito',
  'consumidor/publicidade-oferta',
  'consumidor/contratos-consumidor',
  'consumidor/defesa-em-juizo',
  'consumidor/atendimento-sac',
  'consumidor/atendimento-extrajudicial-mg',
  'consumidor/geral',
  'tributario/competencia-imunidades',
  'tributario/principios',
  'tributario/legislacao-tributaria',
  'tributario/iss',
  'tributario/compensacao',
  'tributario/transacao-tributaria',
  'tributario/contribuicoes-sociais',
  'tributario/geral',
  'penal/teoria-do-crime',
  'penal/aplicacao-lei-penal',
  'penal/honra',
  'penal/prisoes-cautelares',
  'penal/garantias',
  'penal/geral',
  'penal/crimes-patrimoniais',
  'bancario/contratos-bancarios',
  'administrativo/licitacao-14133',
  'administrativo/mandado-seguranca',
  'consumidor/fato-produto-servico',
  'consumidor/fazenda-publica',
  'bancario/alienacao-fiduciaria',
  'trabalhista/vinculo',
  'trabalhista/processo-trabalho',
  'trabalhista/gratuidade-custas',
  'digital/bases-legais',
  'digital/incidentes',
  'digital/dados-sensiveis',
  'digital/criancas-adolescentes',
  'digital/transferencia-internacional',
  'penal/jecrim-menor-ofensividade',
  'civil/responsabilidade-civil',
  'civil/cobranca',
  'geral/prazos',
  'geral/metodologia',
];
