import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowUpRight, CalendarClock, Database, Landmark, MapPinned, Scale, ShieldCheck } from "lucide-react";

function statusLabel(state: string) {
  const labels: Record<string, string> = { not_started: "não iniciado", planned: "planejado", running: "em coleta", partial: "cobertura parcial", completed: "concluído", failed: "falhou", rejected: "rejeitado" };
  return labels[state] ?? state;
}

const formatNumber = new Intl.NumberFormat("pt-BR");

export default function NationalCensusPage() {
  const overview = trpc.nationalCensus.overview.useQuery();
  if (overview.isLoading) return <main className="compendium-loading"><Database size={24} /><p>Carregando a prontidão nacional…</p></main>;
  if (overview.isError || !overview.data) return <main className="compendium-loading error"><Database size={24} /><p>Não foi possível carregar o estado do censo nacional.</p></main>;
  const { readiness: data, distributionStatus, monthly, tribunals, subjects, judgingBodies } = overview.data;
  const run = data.latest;

  return <div className="national-shell">
    <aside className="national-rail"><a className="compendium-brand" href="/"><span className="brand-crest"><Scale size={20} /></span><span><small>Atlas Forense · JEC</small><strong>Prontidão<br />Nacional</strong></span></a><div className="national-rail-copy"><span className="eyebrow">CENSO DATAJUD</span><p>Um censo nacional só existe quando a cobertura, o período e o denominador estão expressos.</p></div><nav><a href="#estado"><span>01</span>Estado da coleta</a><a href="#distribuicoes"><span>02</span>Distribuições</a><a href="#requisitos"><span>03</span>Requisitos</a><a href="#limites"><span>04</span>Limites</a></nav><div className="national-rail-foot"><ShieldCheck size={16} /><p>Sem estatísticas estimadas, amostras tratadas como censo ou números de processos individuais.</p></div></aside>
    <main className="national-main"><header className="national-topbar"><a href="/estrutura" className="back-to-atlas"><ArrowLeft size={16} /> Estrutura interna</a><div><a href="/fontes">Fontes públicas</a><a href="/compendio">Compêndio <ArrowUpRight size={14} /></a></div></header>
      <section className="national-hero"><div><span className="eyebrow">ATLAS FORENSE · CENSO NACIONAL</span><h1>O Brasil entra quando a <em>cobertura</em> entra junto.</h1><p>A camada nacional contém distribuições mensais JEC agregadas por tribunal e UF. Baixas e conclusões comparativas permanecem separadas até validação própria.</p></div><div className="national-mark"><MapPinned size={22} /><span>COBERTURA<br />PRIMEIRO</span><b>27</b></div></section>
      <section className="national-readiness" id="estado"><div className="readiness-overview"><span className="eyebrow">ESTADO ATUAL</span><h2>{statusLabel(data.state)}</h2><p>{run ? run.coverageNote : "Nenhuma execução nacional foi persistida."}</p></div><div className="readiness-numbers"><article><MapPinned size={18} /><span>Cobertura de TJs</span><strong>{data.coveragePct}%</strong><small>{run ? `${run.respondedTribunals} de ${run.expectedTribunals} respondidos` : "Sem execução registrada"}</small></article><article><Database size={18} /><span>Séries agregadas</span><strong>{data.metricRows}</strong><small>Linhas de métrica persistidas</small></article><article><CalendarClock size={18} /><span>Período</span><strong>{run ? `${run.periodStart} — ${run.periodEnd}` : "A definir"}</strong><small>{run ? `Metodologia ${run.methodologyVersion}` : "Aguardando ativação"}</small></article></div></section>
      <section className="national-distributions" id="distribuicoes"><div className="national-section-heading"><div><span className="eyebrow">DISTRIBUIÇÕES · DADO AGREGADO REAL</span><h2>{distributionStatus.label}</h2></div><p>{distributionStatus.limitation}</p></div>{distributionStatus.available ? <><div className="national-data-grid"><div className="national-monthly"><h3>Série mensal Brasil</h3><div>{monthly.map(row => <article key={row.month}><span>{row.month}</span><strong>{formatNumber.format(row.amount)}</strong></article>)}</div></div><div className="national-tribunals"><h3>Maiores volumes no período</h3><ol>{tribunals.map(row => <li key={row.alias}><span><b>{row.alias.toUpperCase()}</b> · {row.uf}</span><strong>{formatNumber.format(row.amount)}</strong></li>)}</ol></div></div><div className="national-facets"><div><h3>12 assuntos mais frequentes</h3><p>Ocorrências de assunto; um mesmo processo pode ter mais de um assunto.</p><ol>{subjects.map(row => <li key={row.code}><span>{row.label}</span><strong>{formatNumber.format(row.amount)}</strong></li>)}</ol></div><div><h3>12 órgãos julgadores mais frequentes</h3><p>Ocorrências por código de órgão informado no DataJud.</p><ol>{judgingBodies.map(row => <li key={row.code}><span>{row.label}</span><strong>{formatNumber.format(row.amount)}</strong></li>)}</ol></div></div></> : <p className="national-empty">Ainda não há série agregada elegível para exibição.</p>}</section>
      <section className="national-requirements" id="requisitos"><div><Landmark size={20} /><span className="eyebrow">PRÉ-CONDIÇÕES DE CENSO</span><h2>O que será exigido antes de publicar comparações.</h2></div><ol><li><span>01</span><p><b>Chave pública e alias testado.</b> Cada tribunal deve responder por rota pública do DataJud, sem salvar credencial.</p></li><li><span>02</span><p><b>Período e métrica homogêneos.</b> Distribuição e baixa serão agregadas por mês, sem misturar níveis de cobertura.</p></li><li><span>03</span><p><b>Registro de falha e ausência.</b> Tribunal sem resposta reduz a cobertura; não será substituído por estimativa.</p></li><li><span>04</span><p><b>Revisão humana antes do relatório.</b> Nenhum ranking, taxa ou conclusão comparativa será publicada sem a ficha metodológica.</p></li></ol></section>
      <section className="national-limits" id="limites"><h2>Distribuição nacional não equivale a taxa, baixa ou resultado processual.</h2><p>Esta página apresenta somente a classe 436, grau JE, por mês de ajuizamento e tribunal, em recorte de 01/01/2025 a 26/08/2026. O período de 2026 é parcial. Baixas, assuntos, órgãos e qualquer conclusão comparativa dependem de coleta e validação específicas.</p></section>
    </main>
  </div>;
}
