import { and, asc, desc, eq, inArray, like, or, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import {
  auditEvents,evidenceReviewItems,evidenceSources,ingestionBatches,jurisprudenceRecords,jurisprudenceTopics,
  legalTheses,legalTopics,metropolitanCoverageRuns,metropolitanJudgingBodyFacets,nationalCensusMetrics,
  nationalCensusRuns,publicDataSources,thesisAuthorities,users,type InsertUser
} from "../drizzle/schema";
import { calculateEvidenceQuality } from "@shared/evidence-quality";
import { describeDocumentFreshness } from "@shared/document-freshness";

let instance:ReturnType<typeof drizzle>|null=null;
export async function getDb(){if(!instance&&process.env.DATABASE_URL){try{instance=drizzle(process.env.DATABASE_URL)}catch(error){console.error("[atlas-db] conexão indisponível",error);instance=null}}return instance}
function requireDb<T>(db:T|null):T{if(!db)throw new Error("Banco de dados não configurado.");return db}

export async function upsertUser(input:InsertUser){const db=requireDb(await getDb());if(!input.openId)throw new Error("openId obrigatório");await db.insert(users).values({...input,lastSignedIn:input.lastSignedIn??new Date()}).onDuplicateKeyUpdate({set:{name:input.name??null,email:input.email??null,loginMethod:input.loginMethod??null,role:input.role??"user",lastSignedIn:new Date()}});const [row]=await db.select().from(users).where(eq(users.openId,input.openId)).limit(1);if(!row)throw new Error("Falha ao persistir usuário.");return row}
export async function getUserByOpenId(openId:string){const db=await getDb();if(!db)return null;const [row]=await db.select().from(users).where(eq(users.openId,openId)).limit(1);return row??null}

export async function getPublicDataSources(){const db=await getDb();if(!db)return[];const rows=await db.select().from(publicDataSources).orderBy(asc(publicDataSources.label));return rows.map(row=>({id:row.id,label:row.label,kind:row.sourceType,baseUrl:row.baseUrl,official:/\.(jus|gov|leg)\.br\b/i.test(row.baseUrl)||/CNJ|STF|STJ|Tribunal|Câmara|Senado/i.test(row.maintainer),status:row.integrationStatus==="integrated"||row.integrationStatus==="ready"?"active":row.integrationStatus==="credential_required"?"limited":"planned",note:row.usageNote,lastVerifiedAt:row.lastVerifiedAt}))}

export async function getCompendiumOverview(){const db=await getDb();if(!db)return{topics:[],theses:[],facets:{tribunals:[],legalAreas:[]},metrics:{decisionCount:0,sourceCount:0,officialSourceCount:0,authorityCount:0}};const [topics,theses,sources,decisionCountRows,authorityCountRows,tribRows,areaRows]=await Promise.all([
 db.select().from(legalTopics).orderBy(asc(legalTopics.pathKey)),db.select().from(legalTheses).orderBy(desc(legalTheses.updatedAt)),db.select().from(evidenceSources),db.select({count:sql<number>`count(*)`}).from(jurisprudenceRecords),db.select({count:sql<number>`count(*)`}).from(thesisAuthorities),db.selectDistinct({value:jurisprudenceRecords.tribunal}).from(jurisprudenceRecords).orderBy(asc(jurisprudenceRecords.tribunal)),db.selectDistinct({value:jurisprudenceRecords.legalArea}).from(jurisprudenceRecords).where(sql`${jurisprudenceRecords.legalArea} is not null`).orderBy(asc(jurisprudenceRecords.legalArea))
 ]);return{topics,theses,facets:{tribunals:tribRows.map(x=>x.value).filter(Boolean) as string[],legalAreas:areaRows.map(x=>x.value).filter(Boolean) as string[]},metrics:{decisionCount:Number(decisionCountRows[0]?.count??0),sourceCount:sources.length,officialSourceCount:sources.filter(s=>s.publicStatus==="official_confirmed"||s.publicStatus==="official_without_number").length,authorityCount:Number(authorityCountRows[0]?.count??0)}}}

export async function getCompendiumQualityOverview(){const db=await getDb();if(!db)return{summary:{averageScore:0,total:0}};const rows=await db.select({record:jurisprudenceRecords,source:evidenceSources}).from(jurisprudenceRecords).leftJoin(evidenceSources,eq(jurisprudenceRecords.sourceId,evidenceSources.id)).limit(2000);const scores=rows.map(({record,source})=>calculateEvidenceQuality({officialSource:source?.publicStatus==="official_confirmed"||source?.publicStatus==="official_without_number",hasSourceUrl:Boolean(source?.sourceUrl),hasDecisionDate:Boolean(record.decisionDate),hasReasoningSummary:Boolean(record.reasoningSummary?.trim()),hasCnjNumber:Boolean(record.cnjNumber?.trim())}).score);return{summary:{averageScore:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,total:scores.length}}}

export async function getCompendiumFreshnessOverview(){const db=await getDb();if(!db)return{summary:{theses:{reviewDue:0,recent:0,notVerified:0}}};const rows=await db.select({lastReviewedAt:legalTheses.lastReviewedAt}).from(legalTheses);const states=rows.map(x=>describeDocumentFreshness(x.lastReviewedAt));return{summary:{theses:{reviewDue:states.filter(x=>x==="review_due").length,recent:states.filter(x=>x==="recent").length,notVerified:states.filter(x=>x==="not_verified").length}}}}

export type CompendiumSearchInput={query?:string;tribunal?:string;city?:string;legalArea?:string;sourceStatus?:typeof jurisprudenceRecords.$inferSelect.sourceStatus;page?:number;pageSize?:number};
export async function searchCompendium(input:CompendiumSearchInput){const db=await getDb();if(!db)return{decisions:[],total:0,page:0,pageSize:input.pageSize??12,searchEngine:"like" as const};const page=input.page??0,pageSize=Math.min(50,input.pageSize??12);const where=[];if(input.tribunal)where.push(eq(jurisprudenceRecords.tribunal,input.tribunal));if(input.city)where.push(eq(jurisprudenceRecords.city,input.city));if(input.legalArea)where.push(eq(jurisprudenceRecords.legalArea,input.legalArea));if(input.sourceStatus)where.push(eq(jurisprudenceRecords.sourceStatus,input.sourceStatus));if(input.query?.trim()){const raw=input.query.trim(),digits=raw.replace(/\D/g,"");where.push(or(like(jurisprudenceRecords.theme,`%${raw}%`),like(jurisprudenceRecords.reasoningSummary,`%${raw}%`),like(jurisprudenceRecords.validationNote,`%${raw}%`),like(jurisprudenceRecords.externalId,`%${raw}%`),digits.length>=15?like(jurisprudenceRecords.cnjNumber,`%${digits}%`):undefined)!) }const predicate=where.length?and(...where):undefined;const [rows,countRows]=await Promise.all([db.select().from(jurisprudenceRecords).where(predicate).orderBy(desc(jurisprudenceRecords.decisionDate),desc(jurisprudenceRecords.id)).limit(pageSize).offset(page*pageSize),db.select({count:sql<number>`count(*)`}).from(jurisprudenceRecords).where(predicate)]);return{decisions:rows,total:Number(countRows[0]?.count??0),page,pageSize,searchEngine:"like" as const}}

export async function getCitationDossier(externalId:string){const db=await getDb();if(!db)return null;const [base]=await db.select({record:jurisprudenceRecords,source:evidenceSources,batch:ingestionBatches}).from(jurisprudenceRecords).innerJoin(evidenceSources,eq(jurisprudenceRecords.sourceId,evidenceSources.id)).innerJoin(ingestionBatches,eq(jurisprudenceRecords.batchId,ingestionBatches.id)).where(eq(jurisprudenceRecords.externalId,externalId)).limit(1);if(!base)return null;const [topicRows,thesisRows,reviewRows,eventRows]=await Promise.all([
 db.select({id:legalTopics.id,pathKey:legalTopics.pathKey,title:legalTopics.title}).from(jurisprudenceTopics).innerJoin(legalTopics,eq(jurisprudenceTopics.topicId,legalTopics.id)).where(eq(jurisprudenceTopics.jurisprudenceId,base.record.id)),
 db.select({id:legalTheses.id,title:legalTheses.title,position:legalTheses.position}).from(thesisAuthorities).innerJoin(legalTheses,eq(thesisAuthorities.thesisId,legalTheses.id)).where(eq(thesisAuthorities.jurisprudenceId,base.record.id)),
 db.select().from(evidenceReviewItems).where(eq(evidenceReviewItems.jurisprudenceId,base.record.id)).limit(1),
 db.select({id:auditEvents.id,action:auditEvents.action,createdAt:auditEvents.createdAt}).from(auditEvents).where(and(eq(auditEvents.entityType,"jurisprudence"),eq(auditEvents.entityKey,externalId))).orderBy(desc(auditEvents.createdAt)).limit(20)
 ]);const r=reviewRows[0];return{record:base.record,source:base.source,batch:base.batch,topics:topicRows,theses:thesisRows,review:r?{status:r.status,priority:r.priority,createdAt:r.createdAt,reviewedAt:r.reviewedAt,requestedReason:"Registro submetido à revisão humana do Atlas.",decisionNote:r.reviewedAt?"Decisão de revisão registrada na trilha administrativa.":null}:null,events:eventRows.map(e=>({...e,note:"Evento de auditoria registrado."}))}}

export async function getEvidenceReviewQueue(input:{status?:"pending"|"approved"|"rejected"|"returned";priority?:"routine"|"elevated"|"urgent";tribunal?:string}={}){const db=await getDb();if(!db)return[];const filters=[];if(input.status)filters.push(eq(evidenceReviewItems.status,input.status));if(input.priority)filters.push(eq(evidenceReviewItems.priority,input.priority));if(input.tribunal)filters.push(eq(jurisprudenceRecords.tribunal,input.tribunal));return db.select({id:evidenceReviewItems.id,status:evidenceReviewItems.status,priority:evidenceReviewItems.priority,requestedReason:evidenceReviewItems.requestedReason,reviewedAt:evidenceReviewItems.reviewedAt,externalId:jurisprudenceRecords.externalId,tribunal:jurisprudenceRecords.tribunal}).from(evidenceReviewItems).innerJoin(jurisprudenceRecords,eq(evidenceReviewItems.jurisprudenceId,jurisprudenceRecords.id)).where(filters.length?and(...filters):undefined).orderBy(desc(evidenceReviewItems.createdAt)).limit(500)}
export async function enqueueEvidenceReview(externalId:string,priority:"routine"|"elevated"|"urgent",requestedReason:string,actorUserId:number){const db=requireDb(await getDb());const [record]=await db.select({id:jurisprudenceRecords.id}).from(jurisprudenceRecords).where(eq(jurisprudenceRecords.externalId,externalId)).limit(1);if(!record)throw new Error("Registro não encontrado.");const [existing]=await db.select().from(evidenceReviewItems).where(eq(evidenceReviewItems.jurisprudenceId,record.id)).limit(1);if(existing)await db.update(evidenceReviewItems).set({status:"pending",priority,requestedReason,assignedToUserId:actorUserId,decisionNote:null,reviewedByUserId:null,reviewedAt:null}).where(eq(evidenceReviewItems.id,existing.id));else await db.insert(evidenceReviewItems).values({jurisprudenceId:record.id,status:"pending",priority,requestedReason,assignedToUserId:actorUserId});await db.insert(auditEvents).values({entityType:"jurisprudence",entityKey:externalId,action:"review_enqueued",actorLabel:`user:${actorUserId}`,note:"Registro encaminhado para revisão humana."});return{success:true}}
export async function decideEvidenceReview(reviewId:number,decision:"approved"|"rejected"|"returned",decisionNote:string,actorUserId:number){const db=requireDb(await getDb());const [row]=await db.select({review:evidenceReviewItems,externalId:jurisprudenceRecords.externalId}).from(evidenceReviewItems).innerJoin(jurisprudenceRecords,eq(evidenceReviewItems.jurisprudenceId,jurisprudenceRecords.id)).where(eq(evidenceReviewItems.id,reviewId)).limit(1);if(!row)throw new Error("Revisão não encontrada.");await db.update(evidenceReviewItems).set({status:decision,decisionNote,reviewedByUserId:actorUserId,reviewedAt:new Date()}).where(eq(evidenceReviewItems.id,reviewId));await db.insert(auditEvents).values({entityType:"jurisprudence",entityKey:row.externalId,action:`review_${decision}`,actorLabel:`user:${actorUserId}`,note:"Decisão administrativa registrada."});return{success:true}}

export async function getNationalCensusReadiness(){const db=await getDb();if(!db)return{state:"empty" as const,latest:null,metricCount:0};const [latest]=await db.select().from(nationalCensusRuns).orderBy(desc(nationalCensusRuns.createdAt)).limit(1);if(!latest)return{state:"empty" as const,latest:null,metricCount:0};const [c]=await db.select({count:sql<number>`count(*)`}).from(nationalCensusMetrics).where(eq(nationalCensusMetrics.runId,latest.id));const metricCount=Number(c?.count??0);return{state:latest.status==="completed"?"ready" as const:latest.status==="partial"?"partial" as const:"controlled" as const,latest,metricCount}}
export async function getNationalCensusOverview(input:{from?:string;to?:string;tribunalAlias?:string}={}){const db=await getDb();const readiness=await getNationalCensusReadiness();if(!db||!readiness.latest)return{readiness,monthly:[],tribunals:[]};const filters=[eq(nationalCensusMetrics.runId,readiness.latest.id),eq(nationalCensusMetrics.metric,"distribution")];if(input.from)filters.push(sql`${nationalCensusMetrics.month} >= ${input.from}` as any);if(input.to)filters.push(sql`${nationalCensusMetrics.month} <= ${input.to}` as any);if(input.tribunalAlias)filters.push(eq(nationalCensusMetrics.tribunalAlias,input.tribunalAlias));const [monthly,tribunals]=await Promise.all([db.select({month:nationalCensusMetrics.month,amount:sql<number>`sum(${nationalCensusMetrics.amount})`}).from(nationalCensusMetrics).where(and(...filters)).groupBy(nationalCensusMetrics.month).orderBy(asc(nationalCensusMetrics.month)),db.select({alias:nationalCensusMetrics.tribunalAlias,uf:nationalCensusMetrics.uf,amount:sql<number>`sum(${nationalCensusMetrics.amount})`}).from(nationalCensusMetrics).where(and(...filters)).groupBy(nationalCensusMetrics.tribunalAlias,nationalCensusMetrics.uf).orderBy(desc(sql`sum(${nationalCensusMetrics.amount})`))]);return{readiness,monthly:monthly.map(x=>({...x,amount:Number(x.amount)})),tribunals:tribunals.map(x=>({...x,amount:Number(x.amount)}))}}
export async function getMetropolitanCoverageOverview(){const db=await getDb();if(!db)return{readiness:{state:"empty" as const,latest:null},municipalities:[]};const [latest]=await db.select().from(metropolitanCoverageRuns).orderBy(desc(metropolitanCoverageRuns.createdAt)).limit(1);if(!latest)return{readiness:{state:"empty" as const,latest:null},municipalities:[]};const rows=await db.select().from(metropolitanJudgingBodyFacets).where(eq(metropolitanJudgingBodyFacets.runId,latest.id)).orderBy(asc(metropolitanJudgingBodyFacets.municipalityName),desc(metropolitanJudgingBodyFacets.amount));const map=new Map<string,{municipalityName:string,municipalityIbgeCode:string,amount:number,bodies:Array<{judgingBodyCode:string;judgingBodyLabel:string;amount:number}>}>();for(const row of rows){const current=map.get(row.municipalityName)??{municipalityName:row.municipalityName,municipalityIbgeCode:row.municipalityIbgeCode,amount:0,bodies:[]};current.amount+=row.amount;current.bodies.push({judgingBodyCode:row.judgingBodyCode,judgingBodyLabel:row.judgingBodyLabel,amount:row.amount});map.set(row.municipalityName,current)}return{readiness:{state:latest.status==="completed"?"ready" as const:"partial" as const,latest},municipalities:[...map.values()]}}

export async function existingExternalIds(ids:string[]){const db=await getDb();if(!db||!ids.length)return new Set<string>();const rows=await db.select({externalId:jurisprudenceRecords.externalId}).from(jurisprudenceRecords).where(inArray(jurisprudenceRecords.externalId,ids));return new Set(rows.map(x=>x.externalId))}
