import { z } from "zod";
import { adminProcedure,protectedProcedure,publicProcedure,router } from "./_core/trpc";
import { THESIS_AUTHORITY_STANCES,THESIS_AUTHORITY_TYPES,THESIS_COUNTERARGUMENT_SOURCE_STATUSES,THESIS_EVIDENCE_IMPORTANCE,THESIS_LEGAL_BASIS_SOURCE_STATUSES,THESIS_LIFECYCLE_STATUSES,THESIS_METRIC_SOURCE_STATUSES,THESIS_REVIEW_DECISIONS,THESIS_REVIEW_STAGES,THESIS_USE_TYPES } from "@shared/thesis-bank";
import { addCounterargument,addEvidenceRequirement,addLegalBasis,addThesisMetric,adminListTheses,adminSnapshot,createDraft,findThesesForCase,linkAuthority,publicThesisDetail,restartReviewCycle,reviewThesis,searchPublicTheses,setThesisScore,thesisBankOverview,transitionThesisStatus,updateDraft } from "./thesis-bank";
const position=z.enum(["favoravel","contraria","condicionada","em_debate"]);const useType=z.enum(THESIS_USE_TYPES);const lifecycle=z.enum(THESIS_LIFECYCLE_STATUSES);const stage=z.enum(THESIS_REVIEW_STAGES);
export const thesisBankRouter=router({
 overview:publicProcedure.query(()=>thesisBankOverview()),
 search:publicProcedure.input(z.object({query:z.string().trim().max(300).optional(),useType:useType.optional(),topicId:z.number().int().positive().optional(),page:z.number().int().min(0).optional(),pageSize:z.number().int().min(1).max(50).optional()})).query(({input})=>searchPublicTheses(input)),
 detail:publicProcedure.input(z.object({publicId:z.string().trim().min(1).max(64)})).query(({input})=>publicThesisDetail(input.publicId)),
 findForCase:protectedProcedure.input(z.object({text:z.string().trim().min(20).max(20000)})).mutation(({input})=>findThesesForCase(input.text)),
 admin:router({
  list:adminProcedure.query(()=>adminListTheses()),
  snapshot:adminProcedure.input(z.object({thesisId:z.number().int().positive()})).query(({input})=>adminSnapshot(input.thesisId)),
  createDraft:adminProcedure.input(z.object({topicId:z.number().int().positive(),title:z.string().trim().min(5).max(500),description:z.string().trim().min(20).max(30000),position,useType,favoredParty:z.string().trim().max(255).optional(),procedure:z.string().trim().max(255).optional(),jurisdiction:z.string().trim().max(255).optional(),instance:z.string().trim().max(128).optional(),argumentation:z.string().trim().max(30000).optional(),assumptions:z.string().trim().max(30000).optional(),requiredFacts:z.string().trim().max(30000).optional(),exceptions:z.string().trim().max(30000).optional(),whenToUse:z.string().trim().max(30000).optional(),whenNotToUse:z.string().trim().max(30000).optional(),likelyDefense:z.string().trim().max(30000).optional(),replyStrategy:z.string().trim().max(30000).optional(),riskNotes:z.string().trim().max(30000).optional()})).mutation(({ctx,input})=>createDraft(input,ctx.user.userId)),
  updateDraft:adminProcedure.input(z.object({thesisId:z.number().int().positive(),title:z.string().trim().min(5).max(500).optional(),description:z.string().trim().min(20).max(30000).optional(),position:position.optional(),useType:useType.optional(),favoredParty:z.string().max(255).nullable().optional(),procedure:z.string().max(255).nullable().optional(),jurisdiction:z.string().max(255).nullable().optional(),instance:z.string().max(128).nullable().optional(),argumentation:z.string().max(30000).nullable().optional(),assumptions:z.string().max(30000).nullable().optional(),requiredFacts:z.string().max(30000).nullable().optional(),exceptions:z.string().max(30000).nullable().optional(),whenToUse:z.string().max(30000).nullable().optional(),whenNotToUse:z.string().max(30000).nullable().optional(),likelyDefense:z.string().max(30000).nullable().optional(),replyStrategy:z.string().max(30000).nullable().optional(),riskNotes:z.string().max(30000).nullable().optional()})).mutation(({input})=>{const{thesisId,...patch}=input;return updateDraft(thesisId,patch)}),
  restartReviewCycle:adminProcedure.input(z.object({thesisId:z.number().int().positive(),note:z.string().trim().min(3).max(1000)})).mutation(({ctx,input})=>restartReviewCycle(input.thesisId,input.note,ctx.user.userId)),
  addLegalBasis:adminProcedure.input(z.object({thesisId:z.number().int().positive(),authorityType:z.enum(THESIS_AUTHORITY_TYPES),norm:z.string().trim().min(2).max(255),provision:z.string().trim().max(255).optional(),relevantText:z.string().trim().max(30000).optional(),officialUrl:z.string().url().max(1024).optional(),sourceStatus:z.enum(THESIS_LEGAL_BASIS_SOURCE_STATUSES),lastVerifiedAt:z.string().datetime().optional()})).mutation(({input})=>{const{thesisId,...rest}=input;return addLegalBasis(thesisId,rest)}),
  addEvidenceRequirement:adminProcedure.input(z.object({thesisId:z.number().int().positive(),label:z.string().trim().min(2).max(255),description:z.string().trim().max(5000).optional(),importance:z.enum(THESIS_EVIDENCE_IMPORTANCE)})).mutation(({input})=>{const{thesisId,...rest}=input;return addEvidenceRequirement(thesisId,rest)}),
  addCounterargument:adminProcedure.input(z.object({thesisId:z.number().int().positive(),relatedThesisId:z.number().int().positive().optional(),title:z.string().trim().min(3).max(500),argument:z.string().trim().min(10).max(30000),recommendedResponse:z.string().trim().max(30000).optional(),sourceStatus:z.enum(THESIS_COUNTERARGUMENT_SOURCE_STATUSES)})).mutation(({input})=>{const{thesisId,...rest}=input;return addCounterargument(thesisId,rest)}),
  linkAuthority:adminProcedure.input(z.object({thesisId:z.number().int().positive(),jurisprudenceExternalId:z.string().trim().min(1).max(191),stance:z.enum(THESIS_AUTHORITY_STANCES),note:z.string().trim().max(5000).optional()})).mutation(({input})=>linkAuthority(input.thesisId,input.jurisprudenceExternalId,input.stance,input.note)),
  setScore:adminProcedure.input(z.object({thesisId:z.number().int().positive(),legalStrength:z.number().min(0).max(100),jurisprudentialConsistency:z.number().min(0).max(100),freshness:z.number().min(0).max(100),evidenceQuality:z.number().min(0).max(100),methodologyNote:z.string().trim().min(10).max(5000)})).mutation(({ctx,input})=>{const{thesisId,...rest}=input;return setThesisScore(thesisId,rest,ctx.user.userId)}),
  addMetric:adminProcedure.input(z.object({thesisId:z.number().int().positive(),tribunal:z.string().trim().max(128).optional(),judgingBody:z.string().trim().max(255).optional(),periodStart:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),periodEnd:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),analyzedCount:z.number().int().positive(),favorableCount:z.number().int().min(0),unfavorableCount:z.number().int().min(0),partialCount:z.number().int().min(0),agreementCount:z.number().int().min(0),methodologyVersion:z.string().trim().min(2).max(64),sampleDefinition:z.string().trim().min(10).max(30000),coverageNote:z.string().trim().min(10).max(30000),sourceStatus:z.enum(THESIS_METRIC_SOURCE_STATUSES)})).mutation(({input})=>{const{thesisId,...rest}=input;return addThesisMetric(thesisId,rest)}),
  review:adminProcedure.input(z.object({thesisId:z.number().int().positive(),stage,decision:z.enum(THESIS_REVIEW_DECISIONS),note:z.string().trim().min(3).max(5000)})).mutation(({ctx,input})=>reviewThesis(input.thesisId,input.stage,input.decision,input.note,ctx.user.userId)),
  transitionStatus:adminProcedure.input(z.object({thesisId:z.number().int().positive(),target:lifecycle,note:z.string().trim().min(3).max(5000)})).mutation(({ctx,input})=>transitionThesisStatus(input.thesisId,input.target,input.note,ctx.user.userId))
 })
});
