// /api/admin/seed-doctrine — Popula LegalDoctrine com base curada (dev only).
// ⚠️ Requer header x-seed-token e NODE_ENV !== production.

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

interface Seed {
  area: string;
  diploma: string;
  numero: string;
  tribunal?: string | null;
  titulo: string;
  textoTrecho: string;
  urlOficial?: string;
  tags: string[];
  vigencia?: string;
}

const SEED: Seed[] = [
  // Constitucional
  { area: "constitucional", diploma: "CF", numero: "art. 1", titulo: "Fundamentos da República", textoTrecho: "A República Federativa do Brasil, formada pela união indissolúvel dos Estados e Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e tem como fundamentos: I - a soberania; II - a cidadania; III - a dignidade da pessoa humana; IV - os valores sociais do trabalho e da livre iniciativa; V - o pluralismo político.", urlOficial: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm", tags: ["fundamentos","estado democratico"], vigencia: "vigente" },
  { area: "constitucional", diploma: "CF", numero: "art. 5", titulo: "Direitos e garantias fundamentais", textoTrecho: "Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do direito à vida, à liberdade, à igualdade, à segurança e à propriedade.", urlOficial: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm", tags: ["direitos fundamentais","devido processo legal","contraditorio","ampla defesa"], vigencia: "vigente" },
  { area: "constitucional", diploma: "CF", numero: "art. 37", titulo: "Princípios da Administração Pública", textoTrecho: "A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência.", urlOficial: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm", tags: ["administrativo","limpas","moralidade"], vigencia: "vigente" },
  { area: "constitucional", diploma: "CF", numero: "art. 133", titulo: "Inviolabilidade do advogado", textoTrecho: "O advogado é indispensável à administração da justiça, sendo inviolável por seus atos e manifestações no exercício da profissão, nos limites da lei.", urlOficial: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm", tags: ["advogado","inviolabilidade"], vigencia: "vigente" },
  { area: "constitucional", diploma: "CF", numero: "art. 225", titulo: "Direito ao meio ambiente ecologicamente equilibrado", textoTrecho: "Todos têm direito ao meio ambiente ecologicamente equilibrado, bem de uso comum do povo e essencial à sadia qualidade de vida, impondo-se ao Poder Público e à coletividade o dever de defendê-lo e preservá-lo para as presentes e futuras gerações.", urlOficial: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm", tags: ["ambiental","meio ambiente"], vigencia: "vigente" },
  // Civil
  { area: "civil", diploma: "CC", numero: "art. 186", titulo: "Ilícito civil", textoTrecho: "Aquele que, por ação ou omissão voluntária, negligência ou imprudência, violar direito e causar dano a outrem, ainda que exclusivamente moral, comete ato ilícito.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l10406.htm", tags: ["responsabilidade civil","ato ilicito"], vigencia: "vigente" },
  { area: "civil", diploma: "CC", numero: "art. 927", titulo: "Obrigação de reparar o dano", textoTrecho: "Aquele que, por ato ilícito (arts. 186 e 187), causa dano a outrem, é obrigado a repará-lo. Parágrafo único. Haverá obrigação de reparar o dano, independentemente de culpa, nos casos especificados em lei, ou quando a atividade normalmente desenvolvida pelo autor do dano implicar, por sua natureza, risco para os direitos de outrem.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l10406.htm", tags: ["responsabilidade civil objetiva","teoria do risco"], vigencia: "vigente" },
  { area: "civil", diploma: "CC", numero: "art. 932", titulo: "Responsabilidade dos pais, tutores, curadores, empregadores etc.", textoTrecho: "São também responsáveis pela reparação civil: I - os pais, pelos filhos menores que estiverem sob sua autoridade e em sua companhia; II - o tutor e o curador, pelos pupilos e curatelados, que se acharem nas mesmas condições; III - o empregador ou comitente, por seus empregados, serviçais e prepostos, no exercício do trabalho que lhes competir, ou em razão dele; IV - os donos de hotéis, hospedarias, casas ou estabelecimentos onde se albergue por dinheiro, moeda corrente, pensão ou galão, os seus hóspedes, moradores, educandos e aprendizes, pelos danos que estes sofrerem; V - os que gratuitamente houverem participado dos produtos do crime, até a concorrente quantia.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l10406.htm", tags: ["responsabilidade objetiva","empregador"], vigencia: "vigente" },
  { area: "civil", diploma: "CC", numero: "art. 205", titulo: "Prescrição geral", textoTrecho: "A prescrição ocorre em dez anos, quando a lei não lhe haja fixado prazo menor.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l10406.htm", tags: ["prescricao","prazo"], vigencia: "vigente" },
  { area: "civil", diploma: "CC", numero: "art. 406", titulo: "Juros legais", textoTrecho: "Quando os juros moratórios não forem convencionados, ou o forem sem taxa estipulada, ou quando provierem de determinação da lei, serão fixados segundo a taxa que estiver em vigor para a mora do pagamento de impostos devidos à Fazenda Nacional.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l10406.htm", tags: ["juros"], vigencia: "vigente" },
  // Processo Civil
  { area: "processo_civil", diploma: "CPC", numero: "art. 17", titulo: "Capacidade processual e legitimação", textoTrecho: "Para propor ou contestar ação é necessário ter legitimidade e interesse. § 1º O interesse processual se verifica pela utilidade que o processo traz à parte.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm", tags: ["legitimidade","interesse"], vigencia: "vigente" },
  { area: "processo_civil", diploma: "CPC", numero: "art. 300", titulo: "Tutela de urgência", textoTrecho: "A tutela de urgência será concedida quando houver elementos que evidenciem a probabilidade do direito e o perigo de dano ou o risco ao resultado útil do processo.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm", tags: ["tutela de urgencia","liminar"], vigencia: "vigente" },
  { area: "processo_civil", diploma: "CPC", numero: "art. 311", titulo: "Tutela da evidência", textoTrecho: "A tutela da evidência será concedida, independentemente da demonstração de perigo de dano ou de risco ao resultado útil do processo, quando: I - ficar caracterizado o abuso do direito de defesa ou o manifesto propósito protelatório da parte; II - como fundamento único ou principal, houver tese firmada em julgamento de casos repetitivos ou em súmula vinculante; III - se tratar de pedido reipersecutório fundado em prova documental adequada e houver tese firmada em julgamento de casos repetitivos ou em súmula vinculante; IV - a prova for suficiente e a tese jurídica estiver firmada em julgamento de casos repetitivos ou em súmula vinculante, podendo o juiz liminarmente pronunciar o direito.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm", tags: ["tutela evidencia","sumula vinculante"], vigencia: "vigente" },
  { area: "processo_civil", diploma: "CPC", numero: "art. 319", titulo: "Requisitos da petição inicial", textoTrecho: "A petição inicial indicará: I - o juízo a que é dirigida; II - a qualificação das partes; III - a causa de pedir; IV - o pedido com as suas especificações; V - o valor da causa; VI - as provas com que o autor pretende demonstrar a verdade dos fatos alegados; VII - a opção do autor pela audiência de conciliação ou de mediação.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm", tags: ["peticao inicial","requisitos"], vigencia: "vigente" },
  { area: "processo_civil", diploma: "CPC", numero: "art. 330", titulo: "Indeferimento da petição inicial", textoTrecho: "A petição inicial será indeferida quando: I - for inepta; II - a parte for manifestamente ilegítima; III - faltar pressuposto processual; IV - faltar condição para o exercício do direito de ação; V - o indeferimento da petição inicial não impede o autor de intentar nova ação.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm", tags: ["indeferimento","peticao"], vigencia: "vigente" },
  { area: "processo_civil", diploma: "CPC", numero: "art. 337", titulo: "Preliminares de contestação", textoTrecho: "Incumbe ao réu, antes de discutir o mérito, alegar: I - inexistência ou nulidade de citação; II - incompetência; III - incorreção do valor da causa; IV - inépcia da inicial; V - conexão; VI - incapacidade processual ou falta de representação; VII - falta de caução ou de outra prestação que a lei exige como preliminar; VIII - indevida concessão da tutela de urgência; IX - coisa julgada; X - convenção de arbitragem; XI - litispendência; XII - coisa julgada; XIII - prescrição; XIV - perempção, litispendência e coisa julgada.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm", tags: ["preliminares","contestacao"], vigencia: "vigente" },
  { area: "processo_civil", diploma: "CPC", numero: "art. 489", titulo: "Fundamentação da sentença", textoTrecho: "São elementos essenciais da sentença: I - o relatório, que conterá os nomes das partes, a identificação do caso, com a suma do pedido e da contestação, e o registro das principais ocorrências havidas no andamento do processo; II - os fundamentos, em que o juiz analisará as questões de fato e de direito; III - o dispositivo, em que o juiz resolverá as questões principais que as partes lhe submeterem.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm", tags: ["sentenca","fundamentacao","art 489"], vigencia: "vigente" },
  { area: "processo_civil", diploma: "CPC", numero: "art. 927", titulo: "Precedentes vinculantes", textoTrecho: "Os juízes e os tribunais observarão: I - as decisões do STF em controle concentrado de constitucionalidade; II - os enunciados de súmula vinculante; III - os acórdãos em IRDR e IAC; IV - os enunciados das súmulas do STF em matéria constitucional e do STJ em matéria infraconstitucional; V - a orientação do plenário ou do órgão especial a que estiverem vinculados.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/l13105.htm", tags: ["precedentes","sumula vinculante","stf","stj"], vigencia: "vigente" },
  // Consumidor
  { area: "consumidor", diploma: "CDC", numero: "art. 6", titulo: "Direitos básicos do consumidor", textoTrecho: "São direitos básicos do consumidor: I - a proteção da vida, saúde e segurança contra os riscos provocados por práticas no fornecimento de produtos e serviços considerados perigosos ou nocivos; II - a educação e divulgação sobre o consumo adequado dos produtos e serviços, asseguradas a liberdade de escolha e a igualdade nas contratações; III - a informação adequada e clara sobre os diferentes produtos e serviços, com especificação correta de quantidade, características, composição, qualidade, tributos incidentes e preço, bem como sobre os riscos que apresentem; IV - a proteção contra a publicidade enganosa e abusiva, métodos comerciais coercitivos ou desleais, bem como contra práticas e cláusulas abusivas ou impostas no fornecimento de produtos e serviços.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l8078.htm", tags: ["consumidor","direitos basicos"], vigencia: "vigente" },
  { area: "consumidor", diploma: "CDC", numero: "art. 14", titulo: "Responsabilidade do fornecedor por defeito do produto/serviço", textoTrecho: "O fornecedor de produtos ou serviços é solidariamente responsável pelos danos causados aos consumidores por defeitos decorrentes de projeto, fabricação, construção, montagem, fórmulas, manipulação, apresentação ou acondicionamento de seus produtos, bem como por informações insuficientes ou inadequadas sobre sua utilização e riscos.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l8078.htm", tags: ["consumidor","responsabilidade objetiva","defeito"], vigencia: "vigente" },
  { area: "consumidor", diploma: "CDC", numero: "art. 42", titulo: "Danos morais na cobrança", textoTrecho: "Na cobrança de débitos, o consumidor inadimplente não será exposto a ridículo, nem será submetido a qualquer tipo de constrangimento ou ameaça. Parágrafo único. O consumidor cobrado em quantia indevida tem direito à repetição do indébito, em valor igual ao dobro do que pagou em excesso, acrescido de correção monetária e juros legais, salvo hipótese de engano justificável.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l8078.htm", tags: ["consumidor","cobranca","dano moral"], vigencia: "vigente" },
  { area: "consumidor", diploma: "CDC", numero: "art. 43", titulo: "Cadastro de inadimplentes", textoTrecho: "O consumidor, sem prejuízo do disposto no art. 86, terá acesso às informações existentes em cadastros, fichas, registros e dados pessoais e de consumo arquivados sobre ele, bem como sobre as suas respectivas fontes. § 1º Os cadastros e dados de consumidores devem ser objetivos, claros, verdadeiros e em linguagem de fácil compreensão, não podendo conter informações negativas referentes a período superior a cinco anos.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l8078.htm", tags: ["consumidor","cadastro","spc","serasa"], vigencia: "vigente" },
  { area: "consumidor", diploma: "CDC", numero: "art. 51", titulo: "Cláusulas abusivas", textoTrecho: "São nulas de pleno direito, entre outras, as cláusulas contratuais relativas ao fornecimento de produtos e serviços que: I - impossibilitem, exonerem ou atenuem a responsabilidade do fornecedor por vícios de qualquer natureza dos produtos e serviços ou impliquem renúncia ao direito de indenização por danos causados; II - subtraiam ao consumidor a opção de rescisão do contrato, nos casos de vícios ocultos;", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l8078.htm", tags: ["consumidor","clausula abusiva","nulidade"], vigencia: "vigente" },
  // Trabalhista
  { area: "trabalhista", diploma: "CLT", numero: "art. 7", titulo: "Direitos dos trabalhadores urbanos e rurais", textoTrecho: "São direitos dos trabalhadores urbanos e rurais, além de outros que visem à melhoria de sua condição social: I - relação de emprego protegida contra despedida arbitrária ou sem justa causa; XXII - redução dos riscos inerentes ao trabalho, por meio de normas de saúde, higiene e segurança; XXXIII - proibição de trabalho noturno, perigoso ou insalubre a menores de dezoito e de qualquer trabalho a menores de quatorze anos.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del5452.htm", tags: ["trabalhista","direitos"], vigencia: "vigente" },
  { area: "trabalhista", diploma: "Súmula TST", numero: "308", titulo: "Prescrição trintenária — contribuição previdenciária", textoTrecho: "A ação de cobrança das contribuições previdenciárias prescreve em trinta anos, observada a redação original do art. 144 da Lei nº 8.213/1991.", urlOficial: "https://www.tst.jus.br/jurisprudencia/sumulas", tags: ["trabalhista","prescricao","previdenciario"], vigencia: "vigente" },
  { area: "trabalhista", diploma: "Súmula TST", numero: "277", titulo: "Convenção coletiva de trabalho — prazo máximo de vigência", textoTrecho: "As condições de trabalho alcançadas por força de sentença normativa vigoram no prazo de 4 (quatro) anos, após o qual poderão ser objeto de nova negociação.", urlOficial: "https://www.tst.jus.br/jurisprudencia/sumulas", tags: ["trabalhista","convenção coletiva","vigencia"], vigencia: "vigente" },
  // Previdenciário
  { area: "previdenciario", diploma: "Lei 8.213", numero: "art. 29", titulo: "Segurado empregado — qualidade de segurado", textoTrecho: "Considera-se segurado empregado, para os efeitos desta Lei, aquele que presta serviço de natureza urbana ou rural à empresa, em caráter não eventual, sob sua subordinação e mediante remuneração, inclusive como diretor empregado.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l8213.htm", tags: ["previdenciario","segurado","vinculo"], vigencia: "vigente" },
  { area: "previdenciario", diploma: "Lei 8.213", numero: "art. 42", titulo: "Aposentadoria por invalidez", textoTrecho: "A aposentadoria por invalidez, uma vez cumprida, quando for o caso, a carência exigida, será devida ao segurado que, estando ou não em gozo de auxílio-doença, for considerado incapaz e insusceptível de reabilitação para o exercício de atividade que lhe garanta a subsistência, e ser-lhe-á paga enquanto permanecer nesta condição.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l8213.htm", tags: ["previdenciario","aposentadoria","invalidez"], vigencia: "vigente" },
  // Penal
  { area: "penal", diploma: "CP", numero: "art. 138", titulo: "Calúnia", textoTrecho: "Caluniar alguém, imputando-lhe falsamente fato definido como crime: Pena — detenção, de seis meses a dois anos, e multa.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848.htm", tags: ["penal","calunia","crimes contra a honra"], vigencia: "vigente" },
  { area: "penal", diploma: "CP", numero: "art. 139", titulo: "Difamação", textoTrecho: "Difamar alguém, imputando-lhe fato ofensivo à sua reputação: Pena — detenção, de três meses a um ano, e multa.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848.htm", tags: ["penal","difamacao"], vigencia: "vigente" },
  { area: "penal", diploma: "CP", numero: "art. 140", titulo: "Injúria", textoTrecho: "Injuriar alguém, ofendendo-lhe a dignidade ou o decoro: Pena — detenção, de um a seis meses, ou multa.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848.htm", tags: ["penal","injuria"], vigencia: "vigente" },
  { area: "penal", diploma: "CP", numero: "art. 155", titulo: "Furto", textoTrecho: "Subtrair, para si ou para outrem, coisa alheia móvel: Pena — reclusão, de um a quatro anos, e multa.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848.htm", tags: ["penal","furto","patrimonio"], vigencia: "vigente" },
  { area: "penal", diploma: "CP", numero: "art. 157", titulo: "Roubo", textoTrecho: "Subtrair coisa móvel alheia, para si ou para outrem, mediante grave ameaça ou violência a pessoa, ou depois de havê-la, por qualquer meio, reduzido à impossibilidade de resistência: Pena — reclusão, de quatro a dez anos, e multa.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848.htm", tags: ["penal","roubo","violencia"], vigencia: "vigente" },
  { area: "penal", diploma: "CP", numero: "art. 154-A", titulo: "Invasão de dispositivo informático", textoTrecho: "Invadir dispositivo informático alheio, conectado ou não à rede de computadores, mediante violação indevida de mecanismo de segurança e com o fim de obter, adulterar ou destruir dados ou informações sem autorização expressa ou tácita do titular do dispositivo ou instalar vulnerabilidades para obter vantagem ilícita: Pena — reclusão, de 1 (um) a 4 (quatro) anos, e multa.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848.htm", tags: ["penal","cibernetico","digital"], vigencia: "vigente" },
  // Processo Penal
  { area: "processo_penal", diploma: "CPP", numero: "art. 5", titulo: "Direitos do preso", textoTrecho: "Em qualquer caso, ao preso será assegurado o direito à identificação dos responsáveis por sua prisão ou por seu interrogatório policial. LIX - o preso será informado de seus direitos, entre os quais o de permanecer calado, sendo-lhe assegurada a assistência da família e de advogado; LX - a prisão de qualquer pessoa e o local onde se encontre serão comunicados imediatamente ao juiz competente e à família do preso ou à pessoa por ele indicada;", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689.htm", tags: ["processo penal","prisao","direitos"], vigencia: "vigente" },
  { area: "processo_penal", diploma: "CPP", numero: "art. 395", titulo: "Rejeição da denúncia", textoTrecho: "A denúncia ou queixa será rejeitada quando: I - for manifestamente inepta; II - faltar pressuposto processual ou condição para o exercício da ação penal; III - faltar justa causa para o exercício da ação penal.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689.htm", tags: ["processo penal","denuncia","rejeicao"], vigencia: "vigente" },
  { area: "processo_penal", diploma: "CPP", numero: "art. 396", titulo: "Citação e resposta do acusado", textoTrecho: "Nos procedimentos ordinário e sumário, oferecida a denúncia ou queixa, o juiz, se não a rejeitar liminarmente, recebê-la-á e ordenará a citação do acusado para responder à acusação, por escrito, no prazo de 10 (dez) dias.", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689.htm", tags: ["processo penal","citacao","resposta"], vigencia: "vigente" },
  { area: "processo_penal", diploma: "CPP", numero: "art. 386", titulo: "Sentença absolutória", textoTrecho: "O juiz absolverá o réu, mencionando a causa na parte dispositiva, desde que reconheça: I - estar provada a inexistência do fato; II - não haver prova suficiente para a condenação; III - não constituir o fato infração penal; IV - estar provado que o réu não concorreu para a infração penal; V - não existir prova suficiente para ter o réu como autor do fato; VI - existirem circunstâncias que excluam o crime (art. 20), ou se houver fundadas dúvidas, sobre sua existência; VII - existir causa excludente da ilicitude ou da culpabilidade do agente (arts. 23, 26 e 28, primeira parte).", urlOficial: "https://www.planalto.gov.br/ccivil_03/decreto-lei/del3689.htm", tags: ["processo penal","sentenca","absolvicao"], vigencia: "vigente" },
  // Tributário
  { area: "tributario", diploma: "CTN", numero: "art. 142", titulo: "Lançamento tributário", textoTrecho: "Compete privativamente à autoridade administrativa constituir o crédito tributário pelo lançamento, assim entendido o procedimento administrativo tendente a verificar a ocorrência do fato gerador da obrigação correspondente, determinar a matéria tributável, calcular o montante do tributo devido, identificar o sujeito passivo e, sendo caso, propor a aplicação da penalidade cabível.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l5172.htm", tags: ["tributario","lancamento"], vigencia: "vigente" },
  { area: "tributario", diploma: "CTN", numero: "art. 173", titulo: "Prescrição e decadência tributárias", textoTrecho: "O direito de a Fazenda Pública constituir o crédito tributário extingue-se após 5 (cinco) anos, contados: I - do primeiro dia do exercício seguinte àquele em que o lançamento poderia ter sido efetuado; II - da data em que se tornar definitiva a decisão que houver anulado, por vício formal, o lançamento anteriormente efetuado.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l5172.htm", tags: ["tributario","decadencia","prescricao"], vigencia: "vigente" },
  { area: "tributario", diploma: "CTN", numero: "art. 97", titulo: "Interpretação da legislação tributária", textoTrecho: "Somente a lei pode estabelecer: I - a instituição de tributos, ou a sua extinção; II - a majoração de tributos, ou a sua redução, ressalvado o disposto nos arts. 21, 26, 39, 57 e 65; III - a definição do fato gerador da obrigação tributária principal, do sujeito passivo, da sua base de cálculo e da sua alíquota; IV - a cominação de penalidades para as ações ou omissões contrárias a seus dispositivos, ou para outras infrações nela definidas; V - as hipóteses de exclusão, suspensão e extinção de créditos tributários, ou de dispensa ou redução de penalidades.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l5172.htm", tags: ["tributario","legalidade","tipicidade"], vigencia: "vigente" },
  // Administrativo
  { area: "administrativo", diploma: "Lei 9.784", numero: "art. 2", titulo: "Princípios do processo administrativo", textoTrecho: "A Administração Pública obedecerá, dentre outros, aos princípios da legalidade, finalidade, motivação, razoabilidade, proporcionalidade, moralidade, ampla defesa, contraditório, segurança jurídica, interesse público e eficiência. Parágrafo único. Nos processos administrativos serão observados, entre outros, os critérios de: I - atuação conforme a lei e o Direito;", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l9784.htm", tags: ["administrativo","principios","devido processo"], vigencia: "vigente" },
  { area: "administrativo", diploma: "Lei 9.784", numero: "art. 50", titulo: "Motivação dos atos administrativos", textoTrecho: "Os atos administrativos deverão ser motivados, com indicação dos fatos e dos fundamentos jurídicos, quando: I - neguem, limitem ou afetem direitos ou interesses; II - imponham ou agravem deveres, encargos ou sanções; III - decidam processos administrativos de concurso ou seleção pública; IV - dispensem ou declarem a inexigibilidade de processo de licitação; V - decidam recursos administrativos; VI - decorram de reexame de ofício; VII - deixem de aplicar jurisprudência firmada sobre a questão ou discrepem de parecer, laudo, proposta ou relatório oficial.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l9784.htm", tags: ["administrativo","motivacao"], vigencia: "vigente" },
  // Ambiental
  { area: "ambiental", diploma: "Lei 9.605", numero: "art. 2", titulo: "Princípio da responsabilidade penal ambiental", textoTrecho: "Quem, de qualquer forma, concorre para a prática dos crimes previstos nesta Lei, incide nas penas a estes cominadas, na medida da sua culpabilidade, bem como o diretor, o administrador, o membro de conselho e de órgão técnico, o auditor, o gerente, o preposto ou mandatário de pessoa jurídica, que, sabendo da conduta criminosa de outrem, deixar de impedir a sua prática, quando podia agir para evitá-la.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm", tags: ["ambiental","crimes ambientais","responsabilidade"], vigencia: "vigente" },
  { area: "ambiental", diploma: "Lei 9.605", numero: "art. 70", titulo: "Infração administrativa ambiental", textoTrecho: "Considera-se infração administrativa ambiental toda ação ou omissão que viole as regras jurídicas de uso, gozo, promoção, proteção e recuperação do meio ambiente.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm", tags: ["ambiental","infracao","auto de infracao"], vigencia: "vigente" },
  { area: "ambiental", diploma: "Lei 6.938", numero: "art. 14", titulo: "Responsabilidade objetiva por dano ambiental", textoTrecho: "Sem prejuízo das penalidades definidas pela legislação federal, estadual e municipal, o poluidor é obrigado, independentemente da existência de culpa, a: I - reparar ou indenizar os danos causados ao meio ambiente e a terceiros, afetados por sua atividade. O Ministério Público da União e dos Estados terá legitimidade para propor ação de responsabilidade civil e criminal por danos causados ao meio ambiente.", urlOficial: "https://www.planalto.gov.br/ccivil_03/leis/l6938.htm", tags: ["ambiental","responsabilidade objetiva","poluidor"], vigencia: "vigente" },
  // Digital
  { area: "digital", diploma: "LGPD", numero: "art. 5", titulo: "Definições (dado pessoal, dado sensível, controlador etc.)", textoTrecho: "Para os fins desta Lei, considera-se: I - dado pessoal: informação relacionada a pessoa natural identificada ou identificável; II - dado pessoal sensível: dado pessoal sobre origem racial ou étnica, convicção religiosa, opinião política, filiação a sindicato ou a organização de caráter religioso, filosófico ou político, dado referente à saúde ou à vida sexual, dado genético ou biométrico, quando vinculado a uma pessoa natural; III - dado anonimizado: dado relativo a titular que não possa ser identificado, considerando a utilização de meios técnicos razoáveis na ocasião de seu tratamento; IV - controlador: pessoa natural ou jurídica, de direito público ou privado, a quem competem as decisões referentes ao tratamento de dados pessoais;", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm", tags: ["digital","lgpd","dado pessoal"], vigencia: "vigente" },
  { area: "digital", diploma: "LGPD", numero: "art. 18", titulo: "Direitos do titular", textoTrecho: "O titular dos dados pessoais tem direito a obter do controlador, em relação aos dados do titular por ele tratados, a qualquer momento e mediante requisição: I - confirmação da existência de tratamento; II - acesso aos dados; III - correção de dados incompletos, inexatos ou desatualizados; IV - anonimização, bloqueio ou eliminação de dados desnecessários, excessivos ou tratados em desconformidade com o disposto nesta Lei; V - portabilidade dos dados a outro fornecedor de serviço ou produto, mediante requisição expressa, de acordo com a regulamentação da autoridade nacional, observados os segredos comercial e industrial; VI - eliminação dos dados pessoais tratados com o consentimento do titular, exceto nas hipóteses previstas no art. 16 desta Lei; VII - informação sobre entidades públicas e privadas com as quais houve compartilhamento de dados; VIII - informação sobre a possibilidade de não fornecer consentimento e suas consequências; IX - revogação do consentimento.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm", tags: ["digital","lgpd","titular","direitos"], vigencia: "vigente" },
  { area: "digital", diploma: "LGPD", numero: "art. 42", titulo: "Responsabilidade por dano em decorrência de violação à LGPD", textoTrecho: "A pessoa natural ou jurídica de direito público ou privado que cause danos em decorrência de violação à legislação de proteção de dados pessoais responde civilmente pelos danos causados. § 1º O controlador ou o operador que, em razão do exercício de atividade de tratamento de dados pessoais, causar a outrem dano patrimonial, moral, individual ou coletivo, em violação à legislação de proteção de dados pessoais, é obrigado a repará-lo.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm", tags: ["digital","lgpd","responsabilidade","dano"], vigencia: "vigente" },
  { area: "digital", diploma: "LGPD", numero: "art. 52", titulo: "Sanções administrativas", textoTrecho: "As sanções aplicáveis pela ANPD, observado o devido processo legal, são: I - advertência; II - multa de até 2% do faturamento da pessoa jurídica, limitada a R$ 50.000.000,00 por infração; III - bloqueio; IV - eliminação dos dados pessoais a que se refere a infração; V - publicização da infração; VI - proibição parcial ou total de exercer atividades de tratamento de dados pessoais.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm", tags: ["digital","lgpd","anpd","sancoes"], vigencia: "vigente" },
  { area: "digital", diploma: "MCI", numero: "art. 7", titulo: "Princípios do uso da internet no Brasil (Marco Civil)", textoTrecho: "O acesso à internet é essencial ao exercício da cidadania, e ao usuário são assegurados os seguintes direitos: I - inviolabilidade da intimidade e da vida privada, sua proteção e indenização pelo dano material ou moral decorrente de sua violação; II - inviolabilidade e sigilo do fluxo de suas comunicações pela internet, salvo por ordem judicial, na forma da lei; III - não fornecimento a terceiros de seus dados pessoais, inclusive registros de conexão, e de acesso a aplicações de internet, salvo mediante consentimento livre, expresso e informado ou nas hipóteses previstas em lei; IV - inviolabilidade e sigilo de comunicações privadas armazenadas, salvo por ordem judicial.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2014/lei/l12965.htm", tags: ["digital","marco civil","internet","privacidade"], vigencia: "vigente" },
  { area: "digital", diploma: "MCI", numero: "art. 19", titulo: "Responsabilidade do provedor de aplicação por conteúdo de terceiros", textoTrecho: "Com o intuito de assegurar a liberdade de expressão e impedir a censura, o provedor de aplicações de internet somente poderá ser responsabilizado civilmente por danos decorrentes de conteúdo gerado por terceiros se, após ordem judicial específica, não tomar as providências para, no âmbito e nos limites técnicos do seu serviço, indisponibilizar o conteúdo apontado como infringente, ressalvadas as disposições legais em contrário.", urlOficial: "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2014/lei/l12965.htm", tags: ["digital","marco civil","provedor","responsabilidade"], vigencia: "vigente" },
  // Súmulas STJ
  { area: "civil", diploma: "Súmula STJ", numero: "359", titulo: "Correção monetária — desapropriação", textoTrecho: "A correção monetária dos valores fixados em sentença, nas desapropriações indiretas, deve ser calculada a partir da data da ocupação do imóvel.", urlOficial: "https://www.stj.jus.br/jurisprudencia/sumulas", tags: ["desapropriacao","correcao monetaria","sumula stj"], vigencia: "vigente" },
  { area: "civil", diploma: "Súmula STJ", numero: "479", titulo: "Instituições financeiras — juros remuneratórios", textoTrecho: "As instituições financeiras podem, para fins de cobrança de juros remuneratórios, aplicar as taxas de mercado divulgadas pela ANBIMA.", urlOficial: "https://www.stj.jus.br/jurisprudencia/sumulas", tags: ["juros","financeiro","sumula stj"], vigencia: "vigente" },
];

export async function POST(req: NextRequest) {
  if (process.env.NODE_ENV === "production") {
    return NextResponse.json({ error: "Seed desabilitado em produção" }, { status: 403 });
  }
  const token = req.headers.get("x-seed-token");
  if (token !== "dev") {
    return NextResponse.json({ error: "Token ausente — use header x-seed-token: dev" }, { status: 401 });
  }

  let inserted = 0;
  let updated = 0;
  for (const item of SEED) {
    const tribunal = item.tribunal ?? null;
    const existing = await db.legalDoctrine.findFirst({
      where: { diploma: item.diploma, numero: item.numero, tribunal },
    });
    const payload = {
      area: item.area,
      diploma: item.diploma,
      numero: item.numero,
      tribunal,
      titulo: item.titulo,
      textoTrecho: item.textoTrecho,
      urlOficial: item.urlOficial ?? null,
      tags: JSON.stringify(item.tags),
      vigencia: item.vigencia ?? "vigente",
      ativo: true,
    };
    if (existing) {
      await db.legalDoctrine.update({ where: { id: existing.id }, data: payload });
      updated++;
    } else {
      await db.legalDoctrine.create({ data: payload });
      inserted++;
    }
  }

  return NextResponse.json({ ok: true, total: SEED.length, inserted, updated });
}

export async function GET() {
  const total = await db.legalDoctrine.count();
  return NextResponse.json({ total });
}