import"dotenv/config";import mysql from"mysql2/promise";const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL não configurada.");const conn=await mysql.createConnection(url);const required=["users","legal_topics","legal_theses","evidence_sources","ingestion_batches","jurisprudence_records","jurisprudence_topics","thesis_authorities","evidence_review_items"];try{const [rows]=await conn.query<any[]>("SELECT table_name FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN (?)",[required]);const found=new Set(rows.map(r=>r.TABLE_NAME??r.table_name));const missing=required.filter(x=>!found.has(x));if(missing.length)throw new Error(`Tabelas-base ausentes: ${missing.join(", ")}. Rode a baseline somente após backup.`);const checks:[string,string][]=[
["legal_theses.topicId órfão","SELECT COUNT(*) c FROM legal_theses t LEFT JOIN legal_topics p ON p.id=t.topicId WHERE p.id IS NULL"],
["jurisprudence_records.batchId órfão","SELECT COUNT(*) c FROM jurisprudence_records r LEFT JOIN ingestion_batches b ON b.id=r.batchId WHERE b.id IS NULL"],
["jurisprudence_records.sourceId órfão","SELECT COUNT(*) c FROM jurisprudence_records r LEFT JOIN evidence_sources s ON s.id=r.sourceId WHERE s.id IS NULL"],
["jurisprudence_topics.jurisprudenceId órfão","SELECT COUNT(*) c FROM jurisprudence_topics x LEFT JOIN jurisprudence_records r ON r.id=x.jurisprudenceId WHERE r.id IS NULL"],
["jurisprudence_topics.topicId órfão","SELECT COUNT(*) c FROM jurisprudence_topics x LEFT JOIN legal_topics t ON t.id=x.topicId WHERE t.id IS NULL"],
["thesis_authorities.thesisId órfão","SELECT COUNT(*) c FROM thesis_authorities x LEFT JOIN legal_theses t ON t.id=x.thesisId WHERE t.id IS NULL"],
["thesis_authorities.jurisprudenceId órfão","SELECT COUNT(*) c FROM thesis_authorities x LEFT JOIN jurisprudence_records r ON r.id=x.jurisprudenceId WHERE r.id IS NULL"],
["evidence_review_items.jurisprudenceId órfão","SELECT COUNT(*) c FROM evidence_review_items x LEFT JOIN jurisprudence_records r ON r.id=x.jurisprudenceId WHERE r.id IS NULL"]];let bad=0;for(const[label,query]of checks){const[result]=await conn.query<any[]>(query);const count=Number(result[0]?.c??0);console.log(`${count===0?"OK":"ERRO"} ${label}: ${count}`);bad+=count}if(bad)throw new Error(`Preflight reprovado: ${bad} relações órfãs.`);console.log("Preflight referencial aprovado para as tabelas legadas.")}finally{await conn.end()}
